services:
  - type: web
    name: fastapi
    runtime: docker
    plan: free
    repo: https://github.com/sterino/tender-backend-ai
    region: frankfurt
    branch: main
    buildFilter:
      paths:
      - app/**
  
